(define (domain robotics)
  (:requirements :strips :equality  :typing)
  (:types location movable manip)
  (:constants door1 door2 door3 door4 door5 door6 door7 door8 door9 door10 - location
  	      lgripper - manip rgripper - manip)
  (:predicates
	   (At ?obj - movable ?loc - location)
           (RobotAt ?loc - location)
	   (InGripper ?obj - movable ?gripper - manip)
	   (IsAccessPointFor ?loc - location ?targetLocation)
	   (OnTray ?obj - movable )
	   (IsTray ?tray - movable )
	   (Topmost ?obj - movable  ?tray - movable )
	   (Object ?obj - movable)
	   (nHeavy ?tray - movable )
	   (Smaller ?obj1 - movable  ?obj2 - movable )
	   (On ?obj1 - movable  ?obj2 - movable )
	   (TempArea ?loc - location)
	   (TrayLocation ?loc - location)
	   (empty ?gripper)
	   (InRoom1 ?loc - location)
	   (InRoom2 ?loc - location)
	   (isgp ?loc - location ?obj - movable ?gripper - manip)
		 (obstructs ?loc - location ?o1 - movable ?o2 - movable)
  )
  


(:functions (total-cost) - number)

 (:action placeOnTray
   :parameters(?lrobot - location ?obj1 - movable ?obj2 - movable  ?tray - movable  ?trayloc - location  ?gripper - manip)
   :precondition(and (Object ?obj1)
   		     (RobotAt ?lrobot) (IsTray ?tray) 
		     (At ?tray ?trayloc)
   		     (IsAccessPointFor ?lrobot ?trayloc) (InGripper ?obj1 ?gripper) 
		     (Topmost ?obj2 ?tray) 
		     (smaller ?obj1 ?obj2)
		     )
   :effect(and (not (InGripper ?obj1 ?gripper)) (OnTray ?obj1) (on ?obj1 ?obj2)
   	       (not (Topmost ?obj2 ?tray)) (Topmost ?obj1 ?tray) 
	       (empty ?gripper) 
	      )
 )	      

 (:action pickTray
  :parameters(?lrobot  - location ?tray - movable  ?trayloc - location )
  :precondition(and (RobotAt ?lrobot) (IsTray ?tray)
  		    (empty lgripper) (empty rgripper)
		    (IsAccessPointFor ?lrobot ?trayloc)
		    (At ?tray ?trayloc)
				(forall (?o - movable) (not (obstructs ?lrobot ?o ?tray)))
		    (nHeavy ?tray))
  :effect(and (not (At ?tray ?trayloc))
	      (not (empty lgripper)) (not (empty rgripper))
	      (InGripper ?tray lgripper) (InGripper ?tray rgripper)
				(forall (?o - movable) (forall (?l - location) (not (obstructs ?l ?tray ?o))))
	 )
 )

 (:action pickFromTray
  :parameters(?lrobot - location  ?tray ?obj - movable  ?obj2  - movable ?trayloc  - location ?gripper - manip)
  :precondition(and (IsTray ?tray) (Object ?obj)
  		  (RobotAt ?lrobot) (IsAccessPointFor ?lrobot ?trayloc)
		  (At ?tray ?trayloc)
		  (Topmost ?obj ?tray) (on ?obj ?obj2)
		  (empty ?gripper)
			(forall (?o - movable) (not (obstructs ?lrobot ?o ?obj)))
		  )
  :effect(and (InGripper ?obj ?gripper) (nHeavy ?tray) (not (ontray ?obj))
  	      (not (Topmost ?obj ?tray)) (not (on ?obj ?obj2))
	      (topmost ?obj2 ?tray) (not (empty ?gripper))
				(forall (?o - movable) (forall (?l - location) (not (obstructs ?l ?obj ?o))))
	      )
)

 (:action putDownTray
  :parameters(?lrobot  - location ?tray  - movable ?ltarget - location )
  :precondition (and (IsTray ?tray) 
  		     (InGripper ?tray lgripper) (InGripper ?tray rgripper) (TrayLocation ?ltarget)
		     (RobotAt ?lrobot) (IsAccessPointFor ?lrobot ?ltarget) 
		     )
  :effect (and (not (InGripper ?tray lgripper)) (not (InGripper ?tray rgripper)) (At ?tray ?ltarget) 
  	        (empty lgripper) (empty rgripper) 
	      )
 )

 (:action putDown
  :parameters(?o1 - movable ?l1 - location  ?l2 - location ?gripper - manip)
  :precondition (and  (Object ?o1)
  		     (InGripper ?o1 ?gripper) (RobotAt ?l2) (TempArea ?l1)
		     (IsAccessPointFor ?l2 ?l1 ))
  :effect (and (not (InGripper ?o1 ?gripper)) (At ?o1 ?l1) (empty ?gripper)
	      )
 )

  (:action moveto_1
     :parameters(?l1  - location ?l2 - location )
     :precondition (and (RobotAt ?l1)
     		   	(InRoom1 ?l1) (InRoom1 ?l2)
     		   	)
     :effect (and (not (RobotAt ?l1)) (RobotAt ?l2) 
  ))

  (:action moveto_2
     :parameters(?l1 - location  ?l2 - location )
     :precondition (and  (RobotAt ?l1)
     		   	(InRoom2 ?l1) (InRoom2 ?l2)
     		   	)
     :effect (and (not (RobotAt ?l1)) (RobotAt ?l2) 
  ))

   (:action moveto_12
      :parameters(?l1 - location  ?l2 - location )
      :precondition (and (RobotAt ?l1))
      :effect (and (not (RobotAt ?l1)) (RobotAt ?l2)
     	      (increase (total-cost) 10)
      	     )
   )

      ; (:action moveToAcrossRoomsTray
      ;    :parameters(?l1 - location  ?l2 - location  ?o - movable ?gripper - manip)
      ;    :precondition (and  (RobotAt ?l1)
      ;    		   	(Ingripper ?o ?gripper) 
      ; 				(Istray ?o) 
      ; 				;(InRoom1 ?l1) (InRoom2 ?l2)
      ;    		   	)
      ;    :effect (and (not (RobotAt ?l1)) (RobotAt ?l2)
      ; 		(increase (total-cost) 10)
      ;   )
      ; )

 (:action grasp
     :parameters(?o1 - movable ?l1 - location ?l2 - location  ?gripper - manip)
     :precondition(and  (At  ?o1 ?l1) (Object ?o1)
     		       (RobotAt ?l2) (IsGP ?l2 ?o1 ?gripper)
		       (empty ?gripper)
					 (forall (?o - movable) (not (obstructs ?l2 ?o ?o1)))
		       )
     :effect (and (InGripper ?o1 ?gripper) (not (At ?o1 ?l1)) (not (empty ?gripper))
		         (forall (?o - movable) (forall (?l - location) (not (obstructs ?l ?o1 ?o))))
 	      )
  )
)