(define (problem dinnerTimeHandoff1) (:domain robotics)
(:objects
object1 object2 object3 object4 object5 object6 object7 object8 object9 object10 tray None - movable

loc_object1 loc_object2 loc_object3 loc_object4 loc_object5 loc_object6 loc_object7 loc_object8 loc_object9 loc_object10 - location
trayLoc1 trayLoc2 - location
destobject1 destobject2 destobject3 destobject4 destobject5 destobject6 destobject7 destobject8 destobject9 destobject10 - location

larm_gp_object1 larm_gp_object2 larm_gp_object3 larm_gp_object4 larm_gp_object5 larm_gp_object6 larm_gp_object7 larm_gp_object8 larm_gp_object9 larm_gp_object10 larm_blf_trayLoc1 - pose
rarm_gp_object1 rarm_gp_object2 rarm_gp_object3 rarm_gp_object4 rarm_gp_object5 rarm_gp_object6 rarm_gp_object7 rarm_gp_object8 rarm_gp_object9 rarm_gp_object10 rarm_blf_trayLoc1 - pose
larm_blf_destobject1 larm_blf_destobject2 larm_blf_destobject3 larm_blf_destobject4 larm_blf_destobject5 larm_blf_destobject6 larm_blf_destobject7 larm_blf_destobject8 larm_blf_destobject9 larm_blf_destobject10 larm_blf_trayLoc2 - pose
rarm_blf_destobject1 rarm_blf_destobject2 rarm_blf_destobject3 rarm_blf_destobject4 rarm_blf_destobject5 rarm_blf_destobject6 rarm_blf_destobject7 rarm_blf_destobject8 rarm_blf_destobject9 rarm_blf_destobject10 rarm_blf_trayLoc2 - pose
robotInitLoc - pose

)

(:init
(At object1 loc_object1)
(At object2 loc_object2)
(At object3 loc_object3)
(At object4 loc_object4)
(At object5 loc_object5)
(At object6 loc_object6)
(At object7 loc_object7)
(At object8 loc_object8)
(At object9 loc_object9)
(At object10 loc_object10)
(At tray trayLoc1)
(RobotAt robotInitLoc)


(Object object1)
(Object object2)
(Object object3)
(Object object4)
(Object object5)
(Object object6)
(Object object7)
(Object object8)
(Object object9)
(Object object10)

(TempArea destobject1)
(TempArea destobject2)
(TempArea destobject3)
(TempArea destobject4)
(TempArea destobject5)
(TempArea destobject6)
(TempArea destobject7)
(TempArea destobject8)
(TempArea destobject9)
(TempArea destobject10)

(Clear destobject1)
(Clear destobject2)
(Clear destobject3)
(Clear destobject4)
(Clear destobject5)
(Clear destobject6)
(Clear destobject7)
(Clear destobject8)
(Clear destobject9)
(Clear destobject10)

(TrayLocation trayLoc1)
(TrayLocation trayLoc2)

(empty rgripper)
(empty lgripper)
(IsTray tray)

(InRoom1 robotInitLoc)

(InRoom1 larm_gp_object1)
(InRoom1 larm_gp_object2)
(InRoom1 larm_gp_object3)
(InRoom1 larm_gp_object4)
(InRoom1 larm_gp_object5)
(InRoom1 larm_gp_object6)
(InRoom1 larm_gp_object7)
(InRoom1 larm_gp_object8)
(InRoom1 larm_gp_object9)
(InRoom1 larm_gp_object10)
(InRoom1 larm_blf_trayLoc1)
(InRoom1 rarm_gp_object1)
(InRoom1 rarm_gp_object2)
(InRoom1 rarm_gp_object3)
(InRoom1 rarm_gp_object4)
(InRoom1 rarm_gp_object5)
(InRoom1 rarm_gp_object6)
(InRoom1 rarm_gp_object7)
(InRoom1 rarm_gp_object8)
(InRoom1 rarm_gp_object9)
(InRoom1 rarm_gp_object10)
(InRoom1 rarm_blf_trayLoc1)

(InRoom2 larm_blf_destobject1)
(InRoom2 larm_blf_destobject2)
(InRoom2 larm_blf_destobject3)
(InRoom2 larm_blf_destobject4)
(InRoom2 larm_blf_destobject5)
(InRoom2 larm_blf_destobject6)
(InRoom2 larm_blf_destobject7)
(InRoom2 larm_blf_destobject8)
(InRoom2 larm_blf_destobject9)
(InRoom2 larm_blf_destobject10)
(InRoom2 larm_blf_trayLoc2)
(InRoom2 rarm_blf_destobject1)
(InRoom2 rarm_blf_destobject2)
(InRoom2 rarm_blf_destobject3)
(InRoom2 rarm_blf_destobject4)
(InRoom2 rarm_blf_destobject5)
(InRoom2 rarm_blf_destobject6)
(InRoom2 rarm_blf_destobject7)
(InRoom2 rarm_blf_destobject8)
(InRoom2 rarm_blf_destobject9)
(InRoom2 rarm_blf_destobject10)
(InRoom2 rarm_blf_trayLoc2)

(IsGP larm_gp_object1 object1 lgripper)
(IsGP larm_gp_object2 object2 lgripper)
(IsGP larm_gp_object3 object3 lgripper)
(IsGP larm_gp_object4 object4 lgripper)
(IsGP larm_gp_object5 object5 lgripper)
(IsGP larm_gp_object6 object6 lgripper)
(IsGP larm_gp_object7 object7 lgripper)
(IsGP larm_gp_object8 object8 lgripper)
(IsGP larm_gp_object9 object9 lgripper)
(IsGP larm_gp_object10 object10 lgripper)
(IsGP rarm_gp_object1 object1 rgripper)
(IsGP rarm_gp_object2 object2 rgripper)
(IsGP rarm_gp_object3 object3 rgripper)
(IsGP rarm_gp_object4 object4 rgripper)
(IsGP rarm_gp_object5 object5 rgripper)
(IsGP rarm_gp_object6 object6 rgripper)
(IsGP rarm_gp_object7 object7 rgripper)
(IsGP rarm_gp_object8 object8 rgripper)
(IsGP rarm_gp_object9 object9 rgripper)
(IsGP rarm_gp_object10 object10 rgripper)

(IsAccessPointForTray larm_blf_trayLoc1 trayLoc1)
(IsAccessPointForTray larm_blf_trayLoc2 trayLoc2)
(IsAccessPointForTray rarm_blf_trayLoc1 trayLoc1)
(IsAccessPointForTray rarm_blf_trayLoc2 trayLoc2)

(IsAccessPointFor larm_blf_destobject1 destobject1 lgripper)
(IsAccessPointFor larm_blf_destobject2 destobject2 lgripper)
(IsAccessPointFor larm_blf_destobject3 destobject3 lgripper)
(IsAccessPointFor larm_blf_destobject4 destobject4 lgripper)
(IsAccessPointFor larm_blf_destobject5 destobject5 lgripper)
(IsAccessPointFor larm_blf_destobject6 destobject6 lgripper)
(IsAccessPointFor larm_blf_destobject7 destobject7 lgripper)
(IsAccessPointFor larm_blf_destobject8 destobject8 lgripper)
(IsAccessPointFor larm_blf_destobject9 destobject9 lgripper)
(IsAccessPointFor larm_blf_destobject10 destobject10 lgripper)
(IsAccessPointFor rarm_blf_destobject1 destobject1 rgripper)
(IsAccessPointFor rarm_blf_destobject2 destobject2 rgripper)
(IsAccessPointFor rarm_blf_destobject3 destobject3 rgripper)
(IsAccessPointFor rarm_blf_destobject4 destobject4 rgripper)
(IsAccessPointFor rarm_blf_destobject5 destobject5 rgripper)
(IsAccessPointFor rarm_blf_destobject6 destobject6 rgripper)
(IsAccessPointFor rarm_blf_destobject7 destobject7 rgripper)
(IsAccessPointFor rarm_blf_destobject8 destobject8 rgripper)
(IsAccessPointFor rarm_blf_destobject9 destobject9 rgripper)
(IsAccessPointFor rarm_blf_destobject10 destobject10 rgripper)

(IsAccessPointFor larm_blf_trayLoc1 trayLoc1 lgripper)
(IsAccessPointFor larm_blf_trayLoc2 trayLoc2 lgripper)
(IsAccessPointFor rarm_blf_trayLoc1 trayLoc1 rgripper)
(IsAccessPointFor rarm_blf_trayLoc2 trayLoc2 rgripper)

(Smaller object1 object2)
(Smaller object1 object4)
(Smaller object1 object5)
(Smaller object1 object3)
(Smaller object1 object6)
(Smaller object1 object7)
(Smaller object1 object8)
(Smaller object1 object9)
(Smaller object1 object10)

(Smaller object2 object1)
(Smaller object2 object4)
(Smaller object2 object5)
(Smaller object2 object3)
(Smaller object2 object6)
(Smaller object2 object7)
(Smaller object2 object8)
(Smaller object2 object9)
(Smaller object2 object10)

(Smaller object4 object2)
(Smaller object4 object1)
(Smaller object4 object5)
(Smaller object4 object3)
(Smaller object4 object6)
(Smaller object4 object7)
(Smaller object4 object8)
(Smaller object4 object9)
(Smaller object4 object10)

(Smaller object5 object2)
(Smaller object5 object4)
(Smaller object5 object1)
(Smaller object5 object3)
(Smaller object5 object6)
(Smaller object5 object7)
(Smaller object5 object8)
(Smaller object5 object9)
(Smaller object5 object10)

(Smaller object3 object2)
(Smaller object3 object4)
(Smaller object3 object5)
(Smaller object3 object1)
(Smaller object3 object6)
(Smaller object3 object7)
(Smaller object3 object8)
(Smaller object3 object9)
(Smaller object3 object10)

(Smaller object6 object2)
(Smaller object6 object4)
(Smaller object6 object5)
(Smaller object6 object3)
(Smaller object6 object1)
(Smaller object6 object7)
(Smaller object6 object8)
(Smaller object6 object9)
(Smaller object6 object10)

(Smaller object7 object2)
(Smaller object7 object4)
(Smaller object7 object5)
(Smaller object7 object3)
(Smaller object7 object1)
(Smaller object7 object6)
(Smaller object7 object8)
(Smaller object7 object9)
(Smaller object7 object10)

(Smaller object8 object2)
(Smaller object8 object4)
(Smaller object8 object5)
(Smaller object8 object3)
(Smaller object8 object1)
(Smaller object8 object7)
(Smaller object8 object6)
(Smaller object8 object9)
(Smaller object8 object10)

(Smaller object9 object2)
(Smaller object9 object4)
(Smaller object9 object5)
(Smaller object9 object3)
(Smaller object9 object1)
(Smaller object9 object7)
(Smaller object9 object8)
(Smaller object9 object6)
(Smaller object9 object10)

(Smaller object10 object2)
(Smaller object10 object4)
(Smaller object10 object5)
(Smaller object10 object3)
(Smaller object10 object1)
(Smaller object10 object7)
(Smaller object10 object8)
(Smaller object10 object9)
(Smaller object10 object6)

(Smaller object1 None)
(Smaller object4 None)
(Smaller object3 None)
(Smaller object2 None)
(Smaller object5 None)
(Smaller object6 None)
(Smaller object7 None)
(Smaller object8 None)
(Smaller object9 None)
(Smaller object10 None)
(Topmost None tray)

(OnLeft larm_gp_object1)
(OnLeft larm_gp_object2)
(OnLeft larm_gp_object3)
(OnLeft larm_gp_object4)
(OnLeft larm_gp_object5)
(OnLeft larm_gp_object6)
(OnLeft larm_gp_object7)
(OnLeft larm_gp_object8)
(OnLeft larm_gp_object9)
(OnLeft larm_gp_object10)
(OnLeft larm_blf_trayLoc1)

(OnLeft rarm_gp_object1)
(OnLeft rarm_gp_object2)
(OnLeft rarm_gp_object3)
(OnLeft rarm_gp_object4)
(OnLeft rarm_gp_object5)
(OnLeft rarm_gp_object6)
(OnLeft rarm_gp_object7)
(OnLeft rarm_gp_object8)
(OnLeft rarm_gp_object9)
(OnLeft rarm_gp_object10)
(OnLeft rarm_blf_trayLoc1)

(OnLeft larm_blf_destobject1)
(OnLeft larm_blf_destobject2)
(OnLeft larm_blf_destobject3)
(OnLeft larm_blf_destobject4)
(OnLeft larm_blf_destobject5)
(OnLeft larm_blf_destobject6)
(OnLeft larm_blf_destobject7)
(OnLeft larm_blf_destobject8)
(OnLeft larm_blf_destobject9)
(OnLeft larm_blf_destobject10)
(OnLeft larm_blf_trayLoc2)

(OnLeft rarm_blf_destobject1)
(OnLeft rarm_blf_destobject2)
(OnLeft rarm_blf_destobject3)
(OnLeft rarm_blf_destobject4)
(OnLeft rarm_blf_destobject5)
(OnLeft rarm_blf_destobject6)
(OnLeft rarm_blf_destobject7)
(OnLeft rarm_blf_destobject8)
(OnLeft rarm_blf_destobject9)
(OnLeft rarm_blf_destobject10)
(OnLeft rarm_blf_trayLoc2)
)

(:goal (and (at object1 destobject1) (at object2 destobject2) (at object3 destobject3) (at object4 destobject4) (at object5 destobject5)
            (at object6 destobject6) (at object7 destobject7) (at object8 destobject8) (at object9 destobject9) (at object10 destobject10)))
            
(:metric minimize (total-cost))

)