(define (problem canworld1) (:domain robotics)
(:objects
object0 object1 object2 object3 object4 object5 object6 object7 object8 object9 object10 object11 - block

loc_object0 loc_object1 loc_object2 loc_object3 loc_object4 loc_object5 loc_object6 loc_object7 loc_object8 loc_object9 loc_object10 loc_object11 rarm_gp_object0 rarm_gp_object1 rarm_gp_object2 rarm_gp_object3 rarm_gp_object4 rarm_gp_object5 rarm_gp_object6 rarm_gp_object7 rarm_gp_object8 rarm_gp_object9 rarm_gp_object10 rarm_gp_object11 larm_gp_object0 larm_gp_object1 larm_gp_object2 larm_gp_object3 larm_gp_object4 larm_gp_object5 larm_gp_object6 larm_gp_object7 larm_gp_object8 larm_gp_object9 larm_gp_object10 larm_gp_object11 - location

robotInitLoc - location
table6 - location

larm_pdp_object0_table6 larm_pdp_object1_table6 larm_pdp_object2_table6 larm_pdp_object3_table6 larm_pdp_object4_table6 larm_pdp_object5_table6 larm_pdp_object6_table6 larm_pdp_object7_table6 larm_pdp_object8_table6 larm_pdp_object9_table6 larm_pdp_object10_table6 larm_pdp_object11_table6  - location

rarm_pdp_object0_table6 rarm_pdp_object1_table6 rarm_pdp_object2_table6 rarm_pdp_object3_table6 rarm_pdp_object4_table6 rarm_pdp_object5_table6 rarm_pdp_object6_table6 rarm_pdp_object7_table6 rarm_pdp_object8_table6 rarm_pdp_object9_table6 rarm_pdp_object10_table6 rarm_pdp_object11_table6  - location


rgripper lgripper - manip

)

(:init
(At object0 loc_object0)
(At object1 loc_object1)
(At object2 loc_object2)
(At object3 loc_object3)
(At object4 loc_object4)
(At object5 loc_object5)
(At object6 loc_object6)
(At object7 loc_object7)
(At object8 loc_object8)
(At object9 loc_object9)
(At object10 loc_object10)
(At object11 loc_object11)
(RobotAt robotInitLoc)

(empty rgripper)
(empty lgripper)

(IsGP rarm_gp_object0 object0 rgripper)
(IsGP rarm_gp_object1 object1 rgripper)
(IsGP rarm_gp_object2 object2 rgripper)
(IsGP rarm_gp_object3 object3 rgripper)
(IsGP rarm_gp_object4 object4 rgripper)
(IsGP rarm_gp_object5 object5 rgripper)
(IsGP rarm_gp_object6 object6 rgripper)
(IsGP rarm_gp_object7 object7 rgripper)
(IsGP rarm_gp_object8 object8 rgripper)
(IsGP rarm_gp_object9 object9 rgripper)
(IsGP rarm_gp_object10 object10 rgripper)
(IsGP rarm_gp_object11 object11 rgripper)

(IsGP larm_gp_object0 object0 lgripper)
(IsGP larm_gp_object1 object1 lgripper)
(IsGP larm_gp_object2 object2 lgripper)
(IsGP larm_gp_object3 object3 lgripper)
(IsGP larm_gp_object4 object4 lgripper)
(IsGP larm_gp_object5 object5 lgripper)
(IsGP larm_gp_object6 object6 lgripper)
(IsGP larm_gp_object7 object7 lgripper)
(IsGP larm_gp_object8 object8 lgripper)
(IsGP larm_gp_object9 object9 lgripper)
(IsGP larm_gp_object10 object10 lgripper)
(IsGP larm_gp_object11 object11 lgripper)

(IsAccessPointFor rarm_pdp_object0_table6 object0 table6 rgripper)
(IsAccessPointFor rarm_pdp_object1_table6 object1  table6 rgripper)
(IsAccessPointFor rarm_pdp_object2_table6 object2 table6 rgripper)
(IsAccessPointFor rarm_pdp_object3_table6 object3 table6 rgripper)
(IsAccessPointFor rarm_pdp_object4_table6 object4 table6 rgripper)
(IsAccessPointFor rarm_pdp_object5_table6 object5 table6 rgripper)
(IsAccessPointFor rarm_pdp_object6_table6 object6 table6 rgripper)
(IsAccessPointFor rarm_pdp_object7_table6 object7 table6 rgripper)
(IsAccessPointFor rarm_pdp_object8_table6 object8 table6 rgripper)
(IsAccessPointFor rarm_pdp_object9_table6 object9 table6 rgripper)
(IsAccessPointFor rarm_pdp_object10_table6 object10 table6 rgripper)
(IsAccessPointFor rarm_pdp_object11_table6 object11 table6 rgripper)

(IsAccessPointFor larm_pdp_object0_table6 object0 table6 lgripper)
(IsAccessPointFor larm_pdp_object1_table6 object1  table6 lgripper)
(IsAccessPointFor larm_pdp_object2_table6 object2 table6 lgripper)
(IsAccessPointFor larm_pdp_object3_table6 object3 table6 lgripper)
(IsAccessPointFor larm_pdp_object4_table6 object4 table6 lgripper)
(IsAccessPointFor larm_pdp_object5_table6 object5 table6 lgripper)
(IsAccessPointFor larm_pdp_object6_table6 object6 table6 lgripper)
(IsAccessPointFor larm_pdp_object7_table6 object7 table6 lgripper)
(IsAccessPointFor larm_pdp_object8_table6 object8 table6 lgripper)
(IsAccessPointFor larm_pdp_object9_table6 object9 table6 lgripper)
(IsAccessPointFor larm_pdp_object10_table6 object10 table6 lgripper)
(IsAccessPointFor larm_pdp_object11_table6 object11 table6 lgripper)

(clear table6)


(doesnt_obstruct rarm_gp_object0 object0 object0)
(doesnt_obstruct rarm_gp_object0 object1 object0)
(doesnt_obstruct rarm_gp_object0 object2 object0)
(doesnt_obstruct rarm_gp_object0 object3 object0)
(doesnt_obstruct rarm_gp_object0 object4 object0)
(doesnt_obstruct rarm_gp_object0 object5 object0)
(doesnt_obstruct rarm_gp_object0 object6 object0)
(doesnt_obstruct rarm_gp_object0 object7 object0)
(doesnt_obstruct rarm_gp_object0 object8 object0)
(doesnt_obstruct rarm_gp_object0 object9 object0)
(doesnt_obstruct rarm_gp_object0 object10 object0)
(doesnt_obstruct rarm_gp_object0 object11 object0)

(doesnt_obstruct rarm_gp_object1 object0 object1)
(doesnt_obstruct rarm_gp_object1 object1 object1)
(doesnt_obstruct rarm_gp_object1 object2 object1)
(doesnt_obstruct rarm_gp_object1 object3 object1)
(doesnt_obstruct rarm_gp_object1 object4 object1)
(doesnt_obstruct rarm_gp_object1 object5 object1)
(doesnt_obstruct rarm_gp_object1 object6 object1)
(doesnt_obstruct rarm_gp_object1 object7 object1)
(doesnt_obstruct rarm_gp_object1 object8 object1)
(doesnt_obstruct rarm_gp_object1 object9 object1)
(doesnt_obstruct rarm_gp_object1 object10 object1)
(doesnt_obstruct rarm_gp_object1 object11 object1)

(doesnt_obstruct rarm_gp_object2 object0 object2)
(doesnt_obstruct rarm_gp_object2 object1 object2)
(doesnt_obstruct rarm_gp_object2 object2 object2)
(doesnt_obstruct rarm_gp_object2 object3 object2)
(doesnt_obstruct rarm_gp_object2 object4 object2)
(doesnt_obstruct rarm_gp_object2 object5 object2)
(doesnt_obstruct rarm_gp_object2 object6 object2)
(doesnt_obstruct rarm_gp_object2 object7 object2)
(doesnt_obstruct rarm_gp_object2 object8 object2)
(doesnt_obstruct rarm_gp_object2 object9 object2)
(doesnt_obstruct rarm_gp_object2 object10 object2)
(doesnt_obstruct rarm_gp_object2 object11 object2)

(doesnt_obstruct rarm_gp_object3 object0 object3)
(doesnt_obstruct rarm_gp_object3 object1 object3)
(doesnt_obstruct rarm_gp_object3 object2 object3)
(doesnt_obstruct rarm_gp_object3 object3 object3)
(doesnt_obstruct rarm_gp_object3 object4 object3)
(doesnt_obstruct rarm_gp_object3 object5 object3)
(doesnt_obstruct rarm_gp_object3 object6 object3)
(doesnt_obstruct rarm_gp_object3 object7 object3)
(doesnt_obstruct rarm_gp_object3 object8 object3)
(doesnt_obstruct rarm_gp_object3 object9 object3)
(doesnt_obstruct rarm_gp_object3 object10 object3)
(doesnt_obstruct rarm_gp_object3 object11 object3)

(doesnt_obstruct rarm_gp_object4 object0 object4)
(doesnt_obstruct rarm_gp_object4 object1 object4)
(doesnt_obstruct rarm_gp_object4 object2 object4)
(doesnt_obstruct rarm_gp_object4 object3 object4)
(doesnt_obstruct rarm_gp_object4 object4 object4)
(doesnt_obstruct rarm_gp_object4 object5 object4)
(doesnt_obstruct rarm_gp_object4 object6 object4)
(doesnt_obstruct rarm_gp_object4 object7 object4)
(doesnt_obstruct rarm_gp_object4 object8 object4)
(doesnt_obstruct rarm_gp_object4 object9 object4)
(doesnt_obstruct rarm_gp_object4 object10 object4)
(doesnt_obstruct rarm_gp_object4 object11 object4)

; (doesnt_obstruct rarm_gp_object5 object0 object5)
; (doesnt_obstruct rarm_gp_object5 object1 object5)
 ; (doesnt_obstruct rarm_gp_object5 object2 object5)
 ; (doesnt_obstruct rarm_gp_object5 object3 object5)
 ; (doesnt_obstruct rarm_gp_object5 object4 object5)
  (doesnt_obstruct rarm_gp_object5 object5 object5)
 ; (doesnt_obstruct rarm_gp_object5 object6 object5)
 ; (doesnt_obstruct rarm_gp_object5 object7 object5)
 ; (doesnt_obstruct rarm_gp_object5 object8 object5)
 ; (doesnt_obstruct rarm_gp_object5 object9 object5)
 ; (doesnt_obstruct rarm_gp_object5 object10 object5)
 ; (doesnt_obstruct rarm_gp_object5 object11 object5)

(doesnt_obstruct rarm_gp_object6 object0 object6)
(doesnt_obstruct rarm_gp_object6 object1 object6)
(doesnt_obstruct rarm_gp_object6 object2 object6)
(doesnt_obstruct rarm_gp_object6 object3 object6)
(doesnt_obstruct rarm_gp_object6 object4 object6)
(doesnt_obstruct rarm_gp_object6 object5 object6)
(doesnt_obstruct rarm_gp_object6 object6 object6)
(doesnt_obstruct rarm_gp_object6 object7 object6)
(doesnt_obstruct rarm_gp_object6 object8 object6)
(doesnt_obstruct rarm_gp_object6 object9 object6)
(doesnt_obstruct rarm_gp_object6 object10 object6)
(doesnt_obstruct rarm_gp_object6 object11 object6)

(doesnt_obstruct rarm_gp_object7 object0 object7)
(doesnt_obstruct rarm_gp_object7 object1 object7)
(doesnt_obstruct rarm_gp_object7 object2 object7)
(doesnt_obstruct rarm_gp_object7 object3 object7)
(doesnt_obstruct rarm_gp_object7 object4 object7)
(doesnt_obstruct rarm_gp_object7 object5 object7)
(doesnt_obstruct rarm_gp_object7 object6 object7)
(doesnt_obstruct rarm_gp_object7 object7 object7)
(doesnt_obstruct rarm_gp_object7 object8 object7)
(doesnt_obstruct rarm_gp_object7 object9 object7)
(doesnt_obstruct rarm_gp_object7 object10 object7)
(doesnt_obstruct rarm_gp_object7 object11 object7)

(doesnt_obstruct rarm_gp_object8 object0 object8)
(doesnt_obstruct rarm_gp_object8 object1 object8)
(doesnt_obstruct rarm_gp_object8 object2 object8)
(doesnt_obstruct rarm_gp_object8 object3 object8)
(doesnt_obstruct rarm_gp_object8 object4 object8)
(doesnt_obstruct rarm_gp_object8 object5 object8)
(doesnt_obstruct rarm_gp_object8 object6 object8)
(doesnt_obstruct rarm_gp_object8 object7 object8)
(doesnt_obstruct rarm_gp_object8 object8 object8)
(doesnt_obstruct rarm_gp_object8 object9 object8)
(doesnt_obstruct rarm_gp_object8 object10 object8)
(doesnt_obstruct rarm_gp_object8 object11 object8)

(doesnt_obstruct rarm_gp_object9 object0 object9)
(doesnt_obstruct rarm_gp_object9 object1 object9)
(doesnt_obstruct rarm_gp_object9 object2 object9)
(doesnt_obstruct rarm_gp_object9 object3 object9)
(doesnt_obstruct rarm_gp_object9 object4 object9)
(doesnt_obstruct rarm_gp_object9 object5 object9)
(doesnt_obstruct rarm_gp_object9 object6 object9)
(doesnt_obstruct rarm_gp_object9 object7 object9)
(doesnt_obstruct rarm_gp_object9 object8 object9)
(doesnt_obstruct rarm_gp_object9 object9 object9)
(doesnt_obstruct rarm_gp_object9 object10 object9)
(doesnt_obstruct rarm_gp_object9 object11 object9)

(doesnt_obstruct rarm_gp_object10 object0 object10)
(doesnt_obstruct rarm_gp_object10 object1 object10)
(doesnt_obstruct rarm_gp_object10 object2 object10)
(doesnt_obstruct rarm_gp_object10 object3 object10)
(doesnt_obstruct rarm_gp_object10 object4 object10)
(doesnt_obstruct rarm_gp_object10 object5 object10)
(doesnt_obstruct rarm_gp_object10 object6 object10)
(doesnt_obstruct rarm_gp_object10 object7 object10)
(doesnt_obstruct rarm_gp_object10 object8 object10)
(doesnt_obstruct rarm_gp_object10 object9 object10)
(doesnt_obstruct rarm_gp_object10 object10 object10)
(doesnt_obstruct rarm_gp_object10 object11 object10)

(doesnt_obstruct rarm_gp_object11 object0 object11)
(doesnt_obstruct rarm_gp_object11 object1 object11)
(doesnt_obstruct rarm_gp_object11 object2 object11)
(doesnt_obstruct rarm_gp_object11 object3 object11)
(doesnt_obstruct rarm_gp_object11 object4 object11)
(doesnt_obstruct rarm_gp_object11 object5 object11)
(doesnt_obstruct rarm_gp_object11 object6 object11)
(doesnt_obstruct rarm_gp_object11 object7 object11)
(doesnt_obstruct rarm_gp_object11 object8 object11)
(doesnt_obstruct rarm_gp_object11 object9 object11)
(doesnt_obstruct rarm_gp_object11 object10 object11)
(doesnt_obstruct rarm_gp_object11 object11 object11)

(doesnt_obstruct larm_gp_object0 object0 object0)
(doesnt_obstruct larm_gp_object0 object1 object0)
(doesnt_obstruct larm_gp_object0 object2 object0)
(doesnt_obstruct larm_gp_object0 object3 object0)
(doesnt_obstruct larm_gp_object0 object4 object0)
(doesnt_obstruct larm_gp_object0 object5 object0)
(doesnt_obstruct larm_gp_object0 object6 object0)
(doesnt_obstruct larm_gp_object0 object7 object0)
(doesnt_obstruct larm_gp_object0 object8 object0)
(doesnt_obstruct larm_gp_object0 object9 object0)
(doesnt_obstruct larm_gp_object0 object10 object0)
(doesnt_obstruct larm_gp_object0 object11 object0)

(doesnt_obstruct larm_gp_object1 object0 object1)
(doesnt_obstruct larm_gp_object1 object1 object1)
(doesnt_obstruct larm_gp_object1 object2 object1)
(doesnt_obstruct larm_gp_object1 object3 object1)
(doesnt_obstruct larm_gp_object1 object4 object1)
(doesnt_obstruct larm_gp_object1 object5 object1)
(doesnt_obstruct larm_gp_object1 object6 object1)
(doesnt_obstruct larm_gp_object1 object7 object1)
(doesnt_obstruct larm_gp_object1 object8 object1)
(doesnt_obstruct larm_gp_object1 object9 object1)
(doesnt_obstruct larm_gp_object1 object10 object1)
(doesnt_obstruct larm_gp_object1 object11 object1)

(doesnt_obstruct larm_gp_object2 object0 object2)
(doesnt_obstruct larm_gp_object2 object1 object2)
(doesnt_obstruct larm_gp_object2 object2 object2)
(doesnt_obstruct larm_gp_object2 object3 object2)
(doesnt_obstruct larm_gp_object2 object4 object2)
(doesnt_obstruct larm_gp_object2 object5 object2)
(doesnt_obstruct larm_gp_object2 object6 object2)
(doesnt_obstruct larm_gp_object2 object7 object2)
(doesnt_obstruct larm_gp_object2 object8 object2)
(doesnt_obstruct larm_gp_object2 object9 object2)
(doesnt_obstruct larm_gp_object2 object10 object2)
(doesnt_obstruct larm_gp_object2 object11 object2)

(doesnt_obstruct larm_gp_object3 object0 object3)
(doesnt_obstruct larm_gp_object3 object1 object3)
(doesnt_obstruct larm_gp_object3 object2 object3)
(doesnt_obstruct larm_gp_object3 object3 object3)
(doesnt_obstruct larm_gp_object3 object4 object3)
(doesnt_obstruct larm_gp_object3 object5 object3)
(doesnt_obstruct larm_gp_object3 object6 object3)
(doesnt_obstruct larm_gp_object3 object7 object3)
(doesnt_obstruct larm_gp_object3 object8 object3)
(doesnt_obstruct larm_gp_object3 object9 object3)
(doesnt_obstruct larm_gp_object3 object10 object3)
(doesnt_obstruct larm_gp_object3 object11 object3)

(doesnt_obstruct larm_gp_object4 object0 object4)
(doesnt_obstruct larm_gp_object4 object1 object4)
(doesnt_obstruct larm_gp_object4 object2 object4)
(doesnt_obstruct larm_gp_object4 object3 object4)
(doesnt_obstruct larm_gp_object4 object4 object4)
(doesnt_obstruct larm_gp_object4 object5 object4)
(doesnt_obstruct larm_gp_object4 object6 object4)
(doesnt_obstruct larm_gp_object4 object7 object4)
(doesnt_obstruct larm_gp_object4 object8 object4)
(doesnt_obstruct larm_gp_object4 object9 object4)
(doesnt_obstruct larm_gp_object4 object10 object4)
(doesnt_obstruct larm_gp_object4 object11 object4)

; (doesnt_obstruct larm_gp_object5 object0 object5)
; (doesnt_obstruct larm_gp_object5 object1 object5)
; (doesnt_obstruct larm_gp_object5 object2 object5)
; (doesnt_obstruct larm_gp_object5 object3 object5)
; (doesnt_obstruct larm_gp_object5 object4 object5)
 (doesnt_obstruct larm_gp_object5 object5 object5)
; (doesnt_obstruct larm_gp_object5 object6 object5)
; (doesnt_obstruct larm_gp_object5 object7 object5)
; (doesnt_obstruct larm_gp_object5 object8 object5)
; (doesnt_obstruct larm_gp_object5 object9 object5)
; (doesnt_obstruct larm_gp_object5 object10 object5)
; (doesnt_obstruct larm_gp_object5 object11 object5)

(doesnt_obstruct larm_gp_object6 object0 object6)
(doesnt_obstruct larm_gp_object6 object1 object6)
(doesnt_obstruct larm_gp_object6 object2 object6)
(doesnt_obstruct larm_gp_object6 object3 object6)
(doesnt_obstruct larm_gp_object6 object4 object6)
(doesnt_obstruct larm_gp_object6 object5 object6)
(doesnt_obstruct larm_gp_object6 object6 object6)
(doesnt_obstruct larm_gp_object6 object7 object6)
(doesnt_obstruct larm_gp_object6 object8 object6)
(doesnt_obstruct larm_gp_object6 object9 object6)
(doesnt_obstruct larm_gp_object6 object10 object6)
(doesnt_obstruct larm_gp_object6 object11 object6)

(doesnt_obstruct larm_gp_object7 object0 object7)
(doesnt_obstruct larm_gp_object7 object1 object7)
(doesnt_obstruct larm_gp_object7 object2 object7)
(doesnt_obstruct larm_gp_object7 object3 object7)
(doesnt_obstruct larm_gp_object7 object4 object7)
(doesnt_obstruct larm_gp_object7 object5 object7)
(doesnt_obstruct larm_gp_object7 object6 object7)
(doesnt_obstruct larm_gp_object7 object7 object7)
(doesnt_obstruct larm_gp_object7 object8 object7)
(doesnt_obstruct larm_gp_object7 object9 object7)
(doesnt_obstruct larm_gp_object7 object10 object7)
(doesnt_obstruct larm_gp_object7 object11 object7)

(doesnt_obstruct larm_gp_object8 object0 object8)
(doesnt_obstruct larm_gp_object8 object1 object8)
(doesnt_obstruct larm_gp_object8 object2 object8)
(doesnt_obstruct larm_gp_object8 object3 object8)
(doesnt_obstruct larm_gp_object8 object4 object8)
(doesnt_obstruct larm_gp_object8 object5 object8)
(doesnt_obstruct larm_gp_object8 object6 object8)
(doesnt_obstruct larm_gp_object8 object7 object8)
(doesnt_obstruct larm_gp_object8 object8 object8)
(doesnt_obstruct larm_gp_object8 object9 object8)
(doesnt_obstruct larm_gp_object8 object10 object8)
(doesnt_obstruct larm_gp_object8 object11 object8)

(doesnt_obstruct larm_gp_object9 object0 object9)
(doesnt_obstruct larm_gp_object9 object1 object9)
(doesnt_obstruct larm_gp_object9 object2 object9)
(doesnt_obstruct larm_gp_object9 object3 object9)
(doesnt_obstruct larm_gp_object9 object4 object9)
(doesnt_obstruct larm_gp_object9 object5 object9)
(doesnt_obstruct larm_gp_object9 object6 object9)
(doesnt_obstruct larm_gp_object9 object7 object9)
(doesnt_obstruct larm_gp_object9 object8 object9)
(doesnt_obstruct larm_gp_object9 object9 object9)
(doesnt_obstruct larm_gp_object9 object10 object9)
(doesnt_obstruct larm_gp_object9 object11 object9)

(doesnt_obstruct larm_gp_object10 object0 object10)
(doesnt_obstruct larm_gp_object10 object1 object10)
(doesnt_obstruct larm_gp_object10 object2 object10)
(doesnt_obstruct larm_gp_object10 object3 object10)
(doesnt_obstruct larm_gp_object10 object4 object10)
(doesnt_obstruct larm_gp_object10 object5 object10)
(doesnt_obstruct larm_gp_object10 object6 object10)
(doesnt_obstruct larm_gp_object10 object7 object10)
(doesnt_obstruct larm_gp_object10 object8 object10)
(doesnt_obstruct larm_gp_object10 object9 object10)
(doesnt_obstruct larm_gp_object10 object10 object10)
(doesnt_obstruct larm_gp_object10 object11 object10)

(doesnt_obstruct larm_gp_object11 object0 object11)
(doesnt_obstruct larm_gp_object11 object1 object11)
(doesnt_obstruct larm_gp_object11 object2 object11)
(doesnt_obstruct larm_gp_object11 object3 object11)
(doesnt_obstruct larm_gp_object11 object4 object11)
(doesnt_obstruct larm_gp_object11 object5 object11)
(doesnt_obstruct larm_gp_object11 object6 object11)
(doesnt_obstruct larm_gp_object11 object7 object11)
(doesnt_obstruct larm_gp_object11 object8 object11)
(doesnt_obstruct larm_gp_object11 object9 object11)
(doesnt_obstruct larm_gp_object11 object10 object11)
(doesnt_obstruct larm_gp_object11 object11 object11)


)

(:goal (and 
;           (empty lgripper)
;	    (RobotAt larm_gp_object11)
;            (forall (?o - block) (doesnt_obstruct larm_gp_object11 ?o object11))
	    (InGripper object5 rgripper)
;	    (At object5 table6)
))

)