(define (domain robotics)
  (:requirements :adl :equality :typing)
  (:types object location manip)
  (:predicates
	   (at ?obj - object ?loc - location)
           (robotat ?loc - location)
	   (ingripper ?obj - object ?gripper - manip)
	   (isaccesspointfor ?loc - location ?targetLoc - location ?gripper - manip)
	   (obstructs ?loc - location ?obj - object ?obj - object)
	   (putdownobstructs ?loc - location ?obj - object ?loc - location)
	   (istargetlocfor ?loc1 - location ?obj - object)
	   (isgp ?loc - location ?obj -object ?gripper - manip)
	   (empty ?gripper - manip)
	   (clear ?loc - location)
  )


  (:action moveto
     :parameters(?l1 - location ?l2 - location)
     :precondition (and  (robotat ?l1))
     :effect (and (not (robotat ?l1)) (robotat ?l2))
  )

 (:action putdown
  :parameters(?o1 - object  ?robotloc - location ?targetLoc - location?gripper - manip)
  :precondition (and (ingripper ?o1 ?gripper) (IsTargetLocFor ?targetLoc ?o1)
                     (robotat ?robotloc) (isaccesspointfor ?robotloc ?targetLoc ?gripper)
		     ;(clear ?target)
		     (forall (?o - object) (not (putdownobstructs ?robotloc ?o ?targetLoc)))
		     )
  :effect (and (at ?o1 ?targetLoc)
               (not (ingripper ?o1 ?gripper))
	       (empty ?gripper)
;	       (not (clear ?target))
	       )
 )

 (:action grasp
     :parameters (?o1 - object ?l1  - location ?gp - location ?gripper - manip)
     :precondition (and (at  ?o1 ?l1)
     		       (robotat ?gp) (isgp ?gp ?o1 ?gripper)
		       (empty ?gripper)
		       (forall (?o - object)
		       	       	    (not (obstructs ?gp ?o ?o1))))
     :effect (and (not (at ?o1 ?l1))
     	          (forall (?o - object) (forall (?l - location) (not (obstructs ?l ?o1 ?o))))
                  (InGripper ?o1 ?gripper)
		  (not (empty ?gripper))
		  (forall (?pdp - location) (forall (?loc2 - location)
		  	  (when (IsTargetLocFor ?pdp ?loc2)
			  (not (putdownobstructs ?pdp ?o1 ?loc2)))))

;		  (clear ?l1)
		  )
 )
)