(define (problem canworld1) (:domain robotics)
(:objects
object0 object1 object2 object3 object4 object5 object6 object7 object8 object9 object10 object11 object12 object13 object14 object15 object16 object17 object18 object19 object20 object21 - object

loc_object0 loc_object1 loc_object2 loc_object3 loc_object4 loc_object5 loc_object6 loc_object7 loc_object8 loc_object9 loc_object10 loc_object11 loc_object12 loc_object13 loc_object14 loc_object15 loc_object16 loc_object17 loc_object18 loc_object19 loc_object20 loc_object21 rarm_gp_object0 rarm_gp_object1 rarm_gp_object2 rarm_gp_object3 rarm_gp_object4 rarm_gp_object5 rarm_gp_object6 rarm_gp_object7 rarm_gp_object8 rarm_gp_object9 rarm_gp_object10 rarm_gp_object11 rarm_gp_object12 rarm_gp_object13 rarm_gp_object14 rarm_gp_object15 rarm_gp_object16 rarm_gp_object17 rarm_gp_object18 rarm_gp_object19 rarm_gp_object20 rarm_gp_object21 larm_gp_object0 larm_gp_object1 larm_gp_object2 larm_gp_object3 larm_gp_object4 larm_gp_object5 larm_gp_object6 larm_gp_object7 larm_gp_object8 larm_gp_object9 larm_gp_object10 larm_gp_object11 larm_gp_object12 larm_gp_object13 larm_gp_object14 larm_gp_object15 larm_gp_object16 larm_gp_object17 larm_gp_object18 larm_gp_object19 larm_gp_object20 larm_gp_object21 - location

table6 robotInitLoc rarm_gp_general, larm_gp_general, rarm_pdp_general_table6, larm_pdp_general_table6 - location

lgripper rgripper - manip

)

(:init
(At object0 loc_object0)
(At object1 loc_object1)
(At object2 loc_object2)
(At object3 loc_object3)
(At object4 loc_object4)
(At object5 loc_object5)
(At object6 loc_object6)
(At object7 loc_object7)
(At object8 loc_object8)
(At object9 loc_object9)
(At object10 loc_object10)
(At object11 loc_object11)
(At object12 loc_object12)
(At object13 loc_object13)
(At object14 loc_object14)
(At object15 loc_object15)
(At object16 loc_object16)
(At object17 loc_object17)
(At object18 loc_object18)
(At object19 loc_object19)
(At object20 loc_object20)
(At object21 loc_object21)

(RobotAt rarm_gp_general)
(RobotAt robotInitLoc)
(RobotAt larm_gp_general)
(RobotAt rarm_pdp_general_table6)
(RobotAt larm_pdp_general_table6)

(empty rgripper)
(empty lgripper)

(IsGP rarm_gp_general object0 rgripper)
(IsGP rarm_gp_general object1 rgripper)
(IsGP rarm_gp_general object2 rgripper)
(IsGP rarm_gp_general object3 rgripper)
(IsGP rarm_gp_general object4 rgripper)
(IsGP rarm_gp_general object5 rgripper)
(IsGP rarm_gp_general object6 rgripper)
(IsGP rarm_gp_general object7 rgripper)
(IsGP rarm_gp_general object8 rgripper)
(IsGP rarm_gp_general object9 rgripper)
(IsGP rarm_gp_general object10 rgripper)
(IsGP rarm_gp_general object11 rgripper)
(IsGP rarm_gp_general object12 rgripper)
(IsGP rarm_gp_general object13 rgripper)
(IsGP rarm_gp_general object14 rgripper)
(IsGP rarm_gp_general object15 rgripper)
(IsGP rarm_gp_general object16 rgripper)
(IsGP rarm_gp_general object17 rgripper)
(IsGP rarm_gp_general object18 rgripper)
(IsGP rarm_gp_general object19 rgripper)
(IsGP rarm_gp_general object20 rgripper)
(IsGP rarm_gp_general object21 rgripper)

(IsGP larm_gp_general object0 lgripper)
(IsGP larm_gp_general object1 lgripper)
(IsGP larm_gp_general object2 lgripper)
(IsGP larm_gp_general object3 lgripper)
(IsGP larm_gp_general object4 lgripper)
(IsGP larm_gp_general object5 lgripper)
(IsGP larm_gp_general object6 lgripper)
(IsGP larm_gp_general object7 lgripper)
(IsGP larm_gp_general object8 lgripper)
(IsGP larm_gp_general object9 lgripper)
(IsGP larm_gp_general object10 lgripper)
(IsGP larm_gp_general object11 lgripper)
(IsGP larm_gp_general object12 lgripper)
(IsGP larm_gp_general object13 lgripper)
(IsGP larm_gp_general object14 lgripper)
(IsGP larm_gp_general object15 lgripper)
(IsGP larm_gp_general object16 lgripper)
(IsGP larm_gp_general object17 lgripper)
(IsGP larm_gp_general object18 lgripper)
(IsGP larm_gp_general object19 lgripper)
(IsGP larm_gp_general object20 lgripper)
(IsGP larm_gp_general object21 lgripper)

(IsAccessPointFor rarm_pdp_general_table6 object0 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object1 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object2 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object3 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object4 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object5 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object6 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object7 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object8 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object9 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object10 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object11 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object12 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object13 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object14 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object15 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object16 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object17 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object18 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object19 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object20 table6 rgripper)
(IsAccessPointFor rarm_pdp_general_table6 object21 table6 rgripper)

(IsAccessPointFor larm_pdp_general_table6 object0 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object1 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object2 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object3 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object4 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object5 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object6 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object7 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object8 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object9 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object10 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object11 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object12 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object13 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object14 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object15 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object16 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object17 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object18 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object19 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object20 table6 lgripper)
(IsAccessPointFor larm_pdp_general_table6 object21 table6 lgripper)


(clear table6)
)

(:goal (and (not (At object1 loc_object1))))


)