(define (problem canworld1) (:domain robotics)
(:objects
object0 object1 object2 object3 object4 object5 object6 object7 object8 object9 object10 object11 object12 object13 object14 object15 object16 object17 object18 object19 object20 object21 object22 object23 object24 object25 object26 object27 object28 object29 object30 object31 object32 object33 object34 object35 object36 object37 object38 object39 object40 object41 object42 object43 object44 object45 object46 object47 object48 object49 - object

loc_object0 loc_object1 loc_object2 loc_object3 loc_object4 loc_object5 loc_object6 loc_object7 loc_object8 loc_object9 loc_object10 loc_object11 loc_object12 loc_object13 loc_object14 loc_object15 loc_object16 loc_object17 loc_object18 loc_object19 loc_object20 loc_object21 loc_object22 loc_object23 loc_object24 loc_object25 loc_object26 loc_object27 loc_object28 loc_object29 loc_object30 loc_object31 loc_object32 loc_object33 loc_object34 loc_object35 loc_object36 loc_object37 loc_object38 loc_object39 loc_object40 loc_object41 loc_object42 loc_object43 loc_object44 loc_object45 loc_object46 loc_object47 loc_object48 loc_object49 rarm_gp_object0 rarm_gp_object1 rarm_gp_object2 rarm_gp_object3 rarm_gp_object4 rarm_gp_object5 rarm_gp_object6 rarm_gp_object7 rarm_gp_object8 rarm_gp_object9 rarm_gp_object10 rarm_gp_object11 rarm_gp_object12 rarm_gp_object13 rarm_gp_object14 rarm_gp_object15 rarm_gp_object16 rarm_gp_object17 rarm_gp_object18 rarm_gp_object19 rarm_gp_object20 rarm_gp_object21 rarm_gp_object22 rarm_gp_object23 rarm_gp_object24 rarm_gp_object25 rarm_gp_object26 rarm_gp_object27 rarm_gp_object28 rarm_gp_object29 rarm_gp_object30 rarm_gp_object31 rarm_gp_object32 rarm_gp_object33 rarm_gp_object34 rarm_gp_object35 rarm_gp_object36 rarm_gp_object37 rarm_gp_object38 rarm_gp_object39 rarm_gp_object40 rarm_gp_object41 rarm_gp_object42 rarm_gp_object43 rarm_gp_object44 rarm_gp_object45 rarm_gp_object46 rarm_gp_object47 rarm_gp_object48 rarm_gp_object49 larm_gp_object0 larm_gp_object1 larm_gp_object2 larm_gp_object3 larm_gp_object4 larm_gp_object5 larm_gp_object6 larm_gp_object7 larm_gp_object8 larm_gp_object9 larm_gp_object10 larm_gp_object11 larm_gp_object12 larm_gp_object13 larm_gp_object14 larm_gp_object15 larm_gp_object16 larm_gp_object17 larm_gp_object18 larm_gp_object19 larm_gp_object20 larm_gp_object21 larm_gp_object22 larm_gp_object23 larm_gp_object24 larm_gp_object25 larm_gp_object26 larm_gp_object27 larm_gp_object28 larm_gp_object29 larm_gp_object30 larm_gp_object31 larm_gp_object32 larm_gp_object33 larm_gp_object34 larm_gp_object35 larm_gp_object36 larm_gp_object37 larm_gp_object38 larm_gp_object39 larm_gp_object40 larm_gp_object41 larm_gp_object42 larm_gp_object43 larm_gp_object44 larm_gp_object45 larm_gp_object46 larm_gp_object47 larm_gp_object48 larm_gp_object49 - location

robotInitLoc - location
table6 - location

larm_pdp_object0_table6 larm_pdp_object1_table6 larm_pdp_object2_table6 larm_pdp_object3_table6 larm_pdp_object4_table6 larm_pdp_object5_table6 larm_pdp_object6_table6 larm_pdp_object7_table6 larm_pdp_object8_table6 larm_pdp_object9_table6 larm_pdp_object10_table6 larm_pdp_object11_table6 larm_pdp_object12_table6 larm_pdp_object13_table6 larm_pdp_object14_table6 larm_pdp_object15_table6 larm_pdp_object16_table6 larm_pdp_object17_table6 larm_pdp_object18_table6 larm_pdp_object19_table6 larm_pdp_object20_table6 larm_pdp_object21_table6 larm_pdp_object22_table6 larm_pdp_object23_table6 larm_pdp_object24_table6 larm_pdp_object25_table6 larm_pdp_object26_table6 larm_pdp_object27_table6 larm_pdp_object28_table6 larm_pdp_object29_table6 larm_pdp_object30_table6 larm_pdp_object31_table6 larm_pdp_object32_table6 larm_pdp_object33_table6 larm_pdp_object34_table6 larm_pdp_object35_table6 larm_pdp_object36_table6 larm_pdp_object37_table6 larm_pdp_object38_table6 larm_pdp_object39_table6 larm_pdp_object40_table6 larm_pdp_object41_table6 larm_pdp_object42_table6 larm_pdp_object43_table6 larm_pdp_object44_table6 larm_pdp_object45_table6 larm_pdp_object46_table6 larm_pdp_object47_table6 larm_pdp_object48_table6 larm_pdp_object49_table6 - location

rarm_pdp_object0_table6 rarm_pdp_object1_table6 rarm_pdp_object2_table6 rarm_pdp_object3_table6 rarm_pdp_object4_table6 rarm_pdp_object5_table6 rarm_pdp_object6_table6 rarm_pdp_object7_table6 rarm_pdp_object8_table6 rarm_pdp_object9_table6 rarm_pdp_object10_table6 rarm_pdp_object11_table6 rarm_pdp_object12_table6 rarm_pdp_object13_table6 rarm_pdp_object14_table6 rarm_pdp_object15_table6 rarm_pdp_object16_table6 rarm_pdp_object17_table6 rarm_pdp_object18_table6 rarm_pdp_object19_table6 rarm_pdp_object20_table6 rarm_pdp_object21_table6 rarm_pdp_object22_table6 rarm_pdp_object23_table6 rarm_pdp_object24_table6 rarm_pdp_object25_table6 rarm_pdp_object26_table6 rarm_pdp_object27_table6 rarm_pdp_object28_table6 rarm_pdp_object29_table6 rarm_pdp_object30_table6 rarm_pdp_object31_table6 rarm_pdp_object32_table6 rarm_pdp_object33_table6 rarm_pdp_object34_table6 rarm_pdp_object35_table6 rarm_pdp_object36_table6 rarm_pdp_object37_table6 rarm_pdp_object38_table6 rarm_pdp_object39_table6 rarm_pdp_object40_table6 rarm_pdp_object41_table6 rarm_pdp_object42_table6 rarm_pdp_object43_table6 rarm_pdp_object44_table6 rarm_pdp_object45_table6 rarm_pdp_object46_table6 rarm_pdp_object47_table6 rarm_pdp_object48_table6 rarm_pdp_object49_table6 - location

rgripper lgripper - manip

)

(:init
(At object0 loc_object0)
(At object1 loc_object1)
(At object2 loc_object2)
(At object3 loc_object3)
(At object4 loc_object4)
(At object5 loc_object5)
(At object6 loc_object6)
(At object7 loc_object7)
(At object8 loc_object8)
(At object9 loc_object9)
(At object10 loc_object10)
(At object11 loc_object11)
(At object12 loc_object12)
(At object13 loc_object13)
(At object14 loc_object14)
(At object15 loc_object15)
(At object16 loc_object16)
(At object17 loc_object17)
(At object18 loc_object18)
(At object19 loc_object19)
(At object20 loc_object20)
(At object21 loc_object21)
(At object22 loc_object22)
(At object23 loc_object23)
(At object24 loc_object24)
(At object25 loc_object25)
(At object26 loc_object26)
(At object27 loc_object27)
(At object28 loc_object28)
(At object29 loc_object29)
(At object30 loc_object30)
(At object31 loc_object31)
(At object32 loc_object32)
(At object33 loc_object33)
(At object34 loc_object34)
(At object35 loc_object35)
(At object36 loc_object36)
(At object37 loc_object37)
(At object38 loc_object38)
(At object39 loc_object39)
(At object40 loc_object40)
(At object41 loc_object41)
(At object42 loc_object42)
(At object43 loc_object43)
(At object44 loc_object44)
(At object45 loc_object45)
(At object46 loc_object46)
(At object47 loc_object47)
(At object48 loc_object48)
(At object49 loc_object49)

(RobotAt robotInitLoc)

(empty rgripper)
(empty lgripper)

(IsGP rarm_gp_object0 object0 rgripper)
(IsGP rarm_gp_object1 object1 rgripper)
(IsGP rarm_gp_object2 object2 rgripper)
(IsGP rarm_gp_object3 object3 rgripper)
(IsGP rarm_gp_object4 object4 rgripper)
(IsGP rarm_gp_object5 object5 rgripper)
(IsGP rarm_gp_object6 object6 rgripper)
(IsGP rarm_gp_object7 object7 rgripper)
(IsGP rarm_gp_object8 object8 rgripper)
(IsGP rarm_gp_object9 object9 rgripper)
(IsGP rarm_gp_object10 object10 rgripper)
(IsGP rarm_gp_object11 object11 rgripper)
(IsGP rarm_gp_object12 object12 rgripper)
(IsGP rarm_gp_object13 object13 rgripper)
(IsGP rarm_gp_object14 object14 rgripper)
(IsGP rarm_gp_object15 object15 rgripper)
(IsGP rarm_gp_object16 object16 rgripper)
(IsGP rarm_gp_object17 object17 rgripper)
(IsGP rarm_gp_object18 object18 rgripper)
(IsGP rarm_gp_object19 object19 rgripper)
(IsGP rarm_gp_object20 object20 rgripper)
(IsGP rarm_gp_object21 object21 rgripper)
(IsGP rarm_gp_object22 object22 rgripper)
(IsGP rarm_gp_object23 object23 rgripper)
(IsGP rarm_gp_object24 object24 rgripper)
(IsGP rarm_gp_object25 object25 rgripper)
(IsGP rarm_gp_object26 object26 rgripper)
(IsGP rarm_gp_object27 object27 rgripper)
(IsGP rarm_gp_object28 object28 rgripper)
(IsGP rarm_gp_object29 object29 rgripper)
(IsGP rarm_gp_object30 object30 rgripper)
(IsGP rarm_gp_object31 object31 rgripper)
(IsGP rarm_gp_object32 object32 rgripper)
(IsGP rarm_gp_object33 object33 rgripper)
(IsGP rarm_gp_object34 object34 rgripper)
(IsGP rarm_gp_object35 object35 rgripper)
(IsGP rarm_gp_object36 object36 rgripper)
(IsGP rarm_gp_object37 object37 rgripper)
(IsGP rarm_gp_object38 object38 rgripper)
(IsGP rarm_gp_object39 object39 rgripper)
(IsGP rarm_gp_object40 object40 rgripper)
(IsGP rarm_gp_object41 object41 rgripper)
(IsGP rarm_gp_object42 object42 rgripper)
(IsGP rarm_gp_object43 object43 rgripper)
(IsGP rarm_gp_object44 object44 rgripper)
(IsGP rarm_gp_object45 object45 rgripper)
(IsGP rarm_gp_object46 object46 rgripper)
(IsGP rarm_gp_object47 object47 rgripper)
(IsGP rarm_gp_object48 object48 rgripper)
(IsGP rarm_gp_object49 object49 rgripper)

(IsGP larm_gp_object0 object0 lgripper)
(IsGP larm_gp_object1 object1 lgripper)
(IsGP larm_gp_object2 object2 lgripper)
(IsGP larm_gp_object3 object3 lgripper)
(IsGP larm_gp_object4 object4 lgripper)
(IsGP larm_gp_object5 object5 lgripper)
(IsGP larm_gp_object6 object6 lgripper)
(IsGP larm_gp_object7 object7 lgripper)
(IsGP larm_gp_object8 object8 lgripper)
(IsGP larm_gp_object9 object9 lgripper)
(IsGP larm_gp_object10 object10 lgripper)
(IsGP larm_gp_object11 object11 lgripper)
(IsGP larm_gp_object12 object12 lgripper)
(IsGP larm_gp_object13 object13 lgripper)
(IsGP larm_gp_object14 object14 lgripper)
(IsGP larm_gp_object15 object15 lgripper)
(IsGP larm_gp_object16 object16 lgripper)
(IsGP larm_gp_object17 object17 lgripper)
(IsGP larm_gp_object18 object18 lgripper)
(IsGP larm_gp_object19 object19 lgripper)
(IsGP larm_gp_object20 object20 lgripper)
(IsGP larm_gp_object21 object21 lgripper)
(IsGP larm_gp_object22 object22 lgripper)
(IsGP larm_gp_object23 object23 lgripper)
(IsGP larm_gp_object24 object24 lgripper)
(IsGP larm_gp_object25 object25 lgripper)
(IsGP larm_gp_object26 object26 lgripper)
(IsGP larm_gp_object27 object27 lgripper)
(IsGP larm_gp_object28 object28 lgripper)
(IsGP larm_gp_object29 object29 lgripper)
(IsGP larm_gp_object30 object30 lgripper)
(IsGP larm_gp_object31 object31 lgripper)
(IsGP larm_gp_object32 object32 lgripper)
(IsGP larm_gp_object33 object33 lgripper)
(IsGP larm_gp_object34 object34 lgripper)
(IsGP larm_gp_object35 object35 lgripper)
(IsGP larm_gp_object36 object36 lgripper)
(IsGP larm_gp_object37 object37 lgripper)
(IsGP larm_gp_object38 object38 lgripper)
(IsGP larm_gp_object39 object39 lgripper)
(IsGP larm_gp_object40 object40 lgripper)
(IsGP larm_gp_object41 object41 lgripper)
(IsGP larm_gp_object42 object42 lgripper)
(IsGP larm_gp_object43 object43 lgripper)
(IsGP larm_gp_object44 object44 lgripper)
(IsGP larm_gp_object45 object45 lgripper)
(IsGP larm_gp_object46 object46 lgripper)
(IsGP larm_gp_object47 object47 lgripper)
(IsGP larm_gp_object48 object48 lgripper)
(IsGP larm_gp_object49 object49 lgripper)

(IsAccessPointFor rarm_pdp_object0_table6 object0 table6 rgripper)
(IsAccessPointFor rarm_pdp_object1_table6 object1  table6 rgripper)
(IsAccessPointFor rarm_pdp_object2_table6 object2 table6 rgripper)
(IsAccessPointFor rarm_pdp_object3_table6 object3 table6 rgripper)
(IsAccessPointFor rarm_pdp_object4_table6 object4 table6 rgripper)
(IsAccessPointFor rarm_pdp_object5_table6 object5 table6 rgripper)
(IsAccessPointFor rarm_pdp_object6_table6 object6 table6 rgripper)
(IsAccessPointFor rarm_pdp_object7_table6 object7 table6 rgripper)
(IsAccessPointFor rarm_pdp_object8_table6 object8 table6 rgripper)
(IsAccessPointFor rarm_pdp_object9_table6 object9 table6 rgripper)
(IsAccessPointFor rarm_pdp_object10_table6 object10 table6 rgripper)
(IsAccessPointFor rarm_pdp_object11_table6 object11 table6 rgripper)
(IsAccessPointFor rarm_pdp_object12_table6 object12 table6 rgripper)
(IsAccessPointFor rarm_pdp_object13_table6 object13 table6 rgripper)
(IsAccessPointFor rarm_pdp_object14_table6 object14 table6 rgripper)
(IsAccessPointFor rarm_pdp_object15_table6 object15 table6 rgripper)
(IsAccessPointFor rarm_pdp_object16_table6 object16 table6 rgripper)
(IsAccessPointFor rarm_pdp_object17_table6 object17 table6 rgripper)
(IsAccessPointFor rarm_pdp_object18_table6 object18 table6 rgripper)
(IsAccessPointFor rarm_pdp_object19_table6 object19 table6 rgripper)
(IsAccessPointFor rarm_pdp_object20_table6 object20 table6 rgripper)
(IsAccessPointFor rarm_pdp_object21_table6 object21 table6 rgripper)
(IsAccessPointFor rarm_pdp_object22_table6 object22 table6 rgripper)
(IsAccessPointFor rarm_pdp_object23_table6 object23 table6 rgripper)
(IsAccessPointFor rarm_pdp_object24_table6 object24 table6 rgripper)
(IsAccessPointFor rarm_pdp_object25_table6 object25 table6 rgripper)
(IsAccessPointFor rarm_pdp_object26_table6 object26 table6 rgripper)
(IsAccessPointFor rarm_pdp_object27_table6 object27 table6 rgripper)
(IsAccessPointFor rarm_pdp_object28_table6 object28 table6 rgripper)
(IsAccessPointFor rarm_pdp_object29_table6 object29 table6 rgripper)
(IsAccessPointFor rarm_pdp_object30_table6 object30 table6 rgripper)
(IsAccessPointFor rarm_pdp_object31_table6 object31 table6 rgripper)
(IsAccessPointFor rarm_pdp_object32_table6 object32 table6 rgripper)
(IsAccessPointFor rarm_pdp_object33_table6 object33 table6 rgripper)
(IsAccessPointFor rarm_pdp_object34_table6 object34 table6 rgripper)
(IsAccessPointFor rarm_pdp_object35_table6 object35 table6 rgripper)
(IsAccessPointFor rarm_pdp_object36_table6 object36 table6 rgripper)
(IsAccessPointFor rarm_pdp_object37_table6 object37 table6 rgripper)
(IsAccessPointFor rarm_pdp_object38_table6 object38 table6 rgripper)
(IsAccessPointFor rarm_pdp_object39_table6 object39 table6 rgripper)
(IsAccessPointFor rarm_pdp_object40_table6 object40 table6 rgripper)
(IsAccessPointFor rarm_pdp_object41_table6 object41 table6 rgripper)
(IsAccessPointFor rarm_pdp_object42_table6 object42 table6 rgripper)
(IsAccessPointFor rarm_pdp_object43_table6 object43 table6 rgripper)
(IsAccessPointFor rarm_pdp_object44_table6 object44 table6 rgripper)
(IsAccessPointFor rarm_pdp_object45_table6 object45 table6 rgripper)
(IsAccessPointFor rarm_pdp_object46_table6 object46 table6 rgripper)
(IsAccessPointFor rarm_pdp_object47_table6 object47 table6 rgripper)
(IsAccessPointFor rarm_pdp_object48_table6 object48 table6 rgripper)
(IsAccessPointFor rarm_pdp_object49_table6 object49 table6 rgripper)

(IsAccessPointFor larm_pdp_object0_table6 object0 table6 lgripper)
(IsAccessPointFor larm_pdp_object1_table6 object1  table6 lgripper)
(IsAccessPointFor larm_pdp_object2_table6 object2 table6 lgripper)
(IsAccessPointFor larm_pdp_object3_table6 object3 table6 lgripper)
(IsAccessPointFor larm_pdp_object4_table6 object4 table6 lgripper)
(IsAccessPointFor larm_pdp_object5_table6 object5 table6 lgripper)
(IsAccessPointFor larm_pdp_object6_table6 object6 table6 lgripper)
(IsAccessPointFor larm_pdp_object7_table6 object7 table6 lgripper)
(IsAccessPointFor larm_pdp_object8_table6 object8 table6 lgripper)
(IsAccessPointFor larm_pdp_object9_table6 object9 table6 lgripper)
(IsAccessPointFor larm_pdp_object10_table6 object10 table6 lgripper)
(IsAccessPointFor larm_pdp_object11_table6 object11 table6 lgripper)
(IsAccessPointFor larm_pdp_object12_table6 object12 table6 lgripper)
(IsAccessPointFor larm_pdp_object13_table6 object13 table6 lgripper)
(IsAccessPointFor larm_pdp_object14_table6 object14 table6 lgripper)
(IsAccessPointFor larm_pdp_object15_table6 object15 table6 lgripper)
(IsAccessPointFor larm_pdp_object16_table6 object16 table6 lgripper)
(IsAccessPointFor larm_pdp_object17_table6 object17 table6 lgripper)
(IsAccessPointFor larm_pdp_object18_table6 object18 table6 lgripper)
(IsAccessPointFor larm_pdp_object19_table6 object19 table6 lgripper)
(IsAccessPointFor larm_pdp_object20_table6 object20 table6 lgripper)
(IsAccessPointFor larm_pdp_object21_table6 object21 table6 lgripper)
(IsAccessPointFor larm_pdp_object22_table6 object22 table6 lgripper)
(IsAccessPointFor larm_pdp_object23_table6 object23 table6 lgripper)
(IsAccessPointFor larm_pdp_object24_table6 object24 table6 lgripper)
(IsAccessPointFor larm_pdp_object25_table6 object25 table6 lgripper)
(IsAccessPointFor larm_pdp_object26_table6 object26 table6 lgripper)
(IsAccessPointFor larm_pdp_object27_table6 object27 table6 lgripper)
(IsAccessPointFor larm_pdp_object28_table6 object28 table6 lgripper)
(IsAccessPointFor larm_pdp_object29_table6 object29 table6 lgripper)
(IsAccessPointFor larm_pdp_object30_table6 object30 table6 lgripper)
(IsAccessPointFor larm_pdp_object31_table6 object31 table6 lgripper)
(IsAccessPointFor larm_pdp_object32_table6 object32 table6 lgripper)
(IsAccessPointFor larm_pdp_object33_table6 object33 table6 lgripper)
(IsAccessPointFor larm_pdp_object34_table6 object34 table6 lgripper)
(IsAccessPointFor larm_pdp_object35_table6 object35 table6 lgripper)
(IsAccessPointFor larm_pdp_object36_table6 object36 table6 lgripper)
(IsAccessPointFor larm_pdp_object37_table6 object37 table6 lgripper)
(IsAccessPointFor larm_pdp_object38_table6 object38 table6 lgripper)
(IsAccessPointFor larm_pdp_object39_table6 object39 table6 lgripper)
(IsAccessPointFor larm_pdp_object40_table6 object40 table6 lgripper)
(IsAccessPointFor larm_pdp_object41_table6 object41 table6 lgripper)
(IsAccessPointFor larm_pdp_object42_table6 object42 table6 lgripper)
(IsAccessPointFor larm_pdp_object43_table6 object43 table6 lgripper)
(IsAccessPointFor larm_pdp_object44_table6 object44 table6 lgripper)
(IsAccessPointFor larm_pdp_object45_table6 object45 table6 lgripper)
(IsAccessPointFor larm_pdp_object46_table6 object46 table6 lgripper)
(IsAccessPointFor larm_pdp_object47_table6 object47 table6 lgripper)
(IsAccessPointFor larm_pdp_object48_table6 object48 table6 lgripper)
(IsAccessPointFor larm_pdp_object49_table6 object49 table6 lgripper)

(clear table6)
)

(:goal (and (not (At object1 loc_object1))))


)